team:
   name: CIDB
   members:
      - user: CBarreiro22
        percentage: 25
      - user: iolivaMISO
        percentage: 25
      - user: david-lyon-uniandes
        percentage: 25
      - user: Tobeny
        percentage: 25
board: https://github.com/orgs/MISW-4301-Desarrollo-Apps-en-la-Nube/projects/110
url: 35.244.141.40
user-management:
  folder: users
  port: 3000
  authors:
    - CBarreiro22
post-management:
  folder: posts
  port: 3001
  authors:
    - david-lyon-uniandes
offer-management:
  folder: offers
  port: 3003
  authors:
    - iolivaMISO
route-management:
  folder: routes
  port: 3002
  authors:
    - Tobeny
rf003-management:
  folder: RF-003
  port: 3006
  authors:
    - iolivaMISO
rf004-management:
  folder: RF-004
  port: 3007
  authors:
    - david-lyon-uniandes
rf005-management:
  folder: RF-005
  port: 3005
  authors:
    - Tobeny
rf006-management:
  folder: RF-006
  port: 3012
  authors:
    - iolivaMISO
    - david-lyon-uniandes
notification-management:
  folder: Notifications
  port: 443
  authors:
    - Tobeny
scores-management:
  folder: scores
  port: 3004
  authors:
    - CBarreiro22
