version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    env_file:
      - ./users/.env.development
    ports:
      - "5432:5432"
    networks:
      - user_net
    volumes:
      - dbdata1:/var/lib/postgresql/data

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: users_container
    restart: always
    ports:
      - "3000:3000"
    networks:
      - user_net
      - app_net
    env_file: users/.env.development
    depends_on:
      - postgres

networks:
  user_net:
    driver: bridge
  app_net:
    driver: bridge

volumes:
  dbdata1: