name: Test coverage
on:
  push:
    branches:
      - main
jobs:
  test_calculator:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10 ]
    steps:
      - uses: actions/checkout@v1
      - name: Instalación de librerías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install coverage pytest python-dotenv wheel flask marshmallow python-abc pytest-cov pytest-mock
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run unit tests
        run: |
          pipenv run pytest --cov=offers/src -v offers/tests/* -s --cov-fail-under=70
          pipenv run pytest --cov=users/src  -v users/tests/* -s --cov-fail-under=70
          pipenv run pytest --cov=posts/src -v posts/tests/* -s --cov-fail-under=70
          pipenv run pytest --cov=routes/src  -v routes/tests/* -s --cov-fail-under=70